In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')

In [2]:
#Display the last 7 rows of the DataFrame
df.tail(7)

,order_id,quantity,item_name,choice_description,item_price
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [3]:
#The data has 4622 rows and 5 columns, the 4 columns have no missing values however, column choice_description has null values since it shows 3376 non null values out of 4622, the data type of object_id, quantity are integers while item_name, choice_description and item_price are objects - string
#summary of the DataFrame including the index dtype and column dtypes, non-null values, and memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [4]:
#Determine how many observations have missing item|_price in the dataset - Zero missing observations
df["item_price"].isnull().sum()

np.int64(0)

In [5]:
#Print the names of all columns in the DataFrame - There are 5 listed columns
df.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [6]:
#Identify which item_name appears most frequently in the orders - most frequent is found using mode, repeated the highest number of times
df["item_name"].mode()

0    Chicken Bowl
Name: item_name, dtype: object

In [7]:
#Determine how many distinct item_name values are present in the dataset
df["item_name"].nunique()

50

In [8]:
#Create a new DataFrame containing only the rows where the item_name is 'Chicken Bowl'.
chicken_bowl = df[df["item_name"] == "Chicken Bowl"]

chicken_bowl.head()

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49

In [9]:
#The 'item_price' column is currently a string (e.g., '$2.39'). Convert it to a float type. You'll need to remove the dollar sign and then convert the data type.
df["item_price"] = (
    df["item_price"]
    .str.replace("$", "", regex=False)
    .astype(float)
)

In [10]:
print(df["item_price"].dtype)

float64

In [11]:
#calculate the average item_price
average_price = df["item_price"].mean()
print ("Average Item Price:", round(average_price, 4))

Average Item Price: 7.4643

In [12]:
#Determine the total number of unique orders in the dataset based on the order_id column
df["order_id"].nunique()

1834

In [13]:
#Section 2
# Calculate total revenue
total_revenue = (df["item_price"] * df["quantity"]).sum()

print(total_revenue)

39237.02

In [14]:
# Create a new column for total revenue per row
df["total_revenue"] = df["item_price"] * df["quantity"]

# Display the first few rows
df.head()

,order_id,quantity,item_name,choice_description,item_price,total_revenue
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96